### ISSUE TITLE
Related paper consultation

### ISSUE THREAD

**Issue by qyshen815** [MatthewPeterKelly/Tractor_Trailer_Control#1]
Hello, thank you very much for your contribution. Your work is excellent, I wonder is there a corresponding paper matching this code?

**Comment by MatthewPeterKelly** [comment]
I did the "tractor trailer control" project for my Q exam, and never wrote
a paper on the topic. However, I did include all of the related math in my
presentation, which can be downloaded here:
https://www.dropbox.com/s/tkof7vu2w0mol67/Q_Exam_Presentation.pdf?dl=1

**Comment by qyshen815** [comment]
Thanks for your reply and help!
